# Use an official Python runtime as a parent image
FROM python:3.10-alpine

# Set the working directory inside the container
WORKDIR /app

# Copy the requirements.txt into the container
COPY requirements.txt /app/

# Install dependencies from the requirements file
RUN pip install --no-cache-dir -r requirements.txt

# Copy the scraper file into the container
COPY scraper.py /app/

# Copy the raw_data_archive directory into the container (add this line)
COPY raw_data_archive /app/raw_data_archive/

# Set the entry point for the scraper
CMD ["python", "scraper.py"]
