FROM python:3.10-alpine

# Set the working directory inside the container
WORKDIR /app

# Copy the requirements.txt into the container
COPY requirements.txt /app/

# Install dependencies from the requirements file
RUN pip install --no-cache-dir -r requirements.txt

RUN pip install --upgrade webdriver-manager

# Copy the scraper file into the container
COPY scraper.py /app/

# Copy the raw_data_archive directory into the container
COPY raw_data_archive /app/raw_data_archive/
COPY download /app/download/

# Run scraper.py
CMD ["python", "scraper.py"]
